### ISSUE TITLE
运行train_stssl.py报错

### ISSUE THREAD

**Issue by wslbby** [YanhaoWu/CVPR2023_STSSL#5]
Yanhao Wu您好，感谢您的贡献。根据您readme中的设置运行train_stssl.py，在data preprocessing完成之后，遇到如下报错，似乎是dataloader的问题，GPU只有一块Titan RTX，不知是否这个原因相关
```
Traceback (most recent call last):
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py", line 124, in <module>
    trainer.fit(model_sem_kitti)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 307, in ddp_train
    results = self.train_or_test()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 542, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 85, in profile_iterable
    value = next(iterator)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 46, in _with_is_last
    last = next(it)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/data_utils/collations.py", line 180, in __call__
    points_i = np.asarray(points_i)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

Traceback (most recent call last):
  File "train_stssl.py", line 77, in <module>
    result = subprocess.run(['python', str(args.train_command), '--stage', str(0), '--stop_epoch', str(int(stop_epoch)), '--model_save_dir', str(model_save_dir), '--segment_pathbase', segment_save_path],  stdout = train_file, check=True)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py', '--stage', '0', '--stop_epoch', '160', '--model_save_dir', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/model_save/0/stage1', '--segment_pathbase', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/STSSL_Segments/']' returned non-zero exit status 1.
```

**Comment by YanhaoWu** [comment]
这个大概率是因为你numpy版本太高了，老一点版本的numpy可以把不同shape的list强行np.array()处理，但是新版本的不让。我自己最近更新过后重写一份绕开np.array的代码，过一段时间可以更新一下，最近这两天有点别的事。
so, 你可以降低numpy版本，或者把数据收集放到trainer里面去，避开这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanhaoWu/STSSL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 下午3:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YanhaoWu/STSSL] 运行train_stssl.py报错 (Issue #5)





 
Yanhao Wu您好，感谢您的贡献。根据您readme中的设置运行train_stssl.py，在data preprocessing完成之后，遇到如下报错，似乎是dataloader的问题，GPU只有一块Titan RTX，不知是否这个原因相关
 Traceback (most recent call last):   File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py", line 124, in <module&gt;     trainer.fit(model_sem_kitti)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit     results = self.accelerator_backend.train()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train     results = self.ddp_train(process_idx=self.task_idx, model=model)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 307, in ddp_train     results = self.train_or_test()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test     results = self.trainer.train()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train     self.train_loop.run_training_epoch()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 542, in run_training_epoch     for batch_idx, (batch, is_last_batch) in train_dataloader:   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 85, in profile_iterable     value = next(iterator)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 46, in _with_is_last     last = next(it)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__     data = self._next_data()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data     return self._process_data(data)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data     data.reraise()   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise     raise self.exc_type(msg) ValueError: Caught ValueError in DataLoader worker process 0. Original Traceback (most recent call last):   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop     data = fetcher.fetch(index)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch     return self.collate_fn(data)   File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/data_utils/collations.py", line 180, in __call__     points_i = np.asarray(points_i) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part. Traceback (most recent call last):   File "train_stssl.py", line 77, in <module&gt;     result = subprocess.run(['python', str(args.train_command), '--stage', str(0), '--stop_epoch', str(int(stop_epoch)), '--model_save_dir', str(model_save_dir), '--segment_pathbase', segment_save_path],  stdout = train_file, check=True)   File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/subprocess.py", line 516, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['python', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py', '--stage', '0', '--stop_epoch', '160', '--model_save_dir', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/model_save/0/stage1', '--segment_pathbase', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/STSSL_Segments/']' returned non-zero exit status 1.

**Comment by wslbby** [comment]
抱歉打扰了，降级后上一个错误解决了，出现了另一个错误
```
Traceback (most recent call last):
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py", line 124, in <module>
    trainer.fit(model_sem_kitti)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 307, in ddp_train
    results = self.train_or_test()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 550, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 718, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 485, in optimizer_step
    model_ref.optimizer_step(
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1298, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 286, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 144, in __optimizer_step
    optimizer.step(closure=closure, *args, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/optim/sgd.py", line 87, in step
    loss = closure()
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 708, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 806, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 319, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 164, in training_step
    return self._step(args)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 178, in _step
    output = self.trainer.model(*args)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/site-packages/pytorch_lightning/overrides/data_parallel.py", line 192, in forward
    output = self.module.training_step(*inputs[0], **kwargs[0])
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/trainer/stssl_trainer.py", line 75, in training_step
    loss =  self.train_step_1(batch, batch_nb)
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/trainer/stssl_trainer.py", line 61, in train_step_1
    loss = self.train_model.forward_intra_frames(xi, xj, [si, sj], self.pix_deal)
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/models/byol_pix.py", line 102, in forward_intra_frames
    h_qs = list_segments_points(representation_q.C, representation_q.F, segments[0])
  File "/home/kjzhao/zhaokj_home/projects/2024/STSSL/data_utils/collations.py", line 29, in list_segments_points
    segment_coord = p_coord[batch_ind][segment_ind][:,:]
IndexError: The shape of the mask [20000] at index 0 does not match the shape of the indexed tensor [65793, 4] at index 0
Traceback (most recent call last):
  File "train_stssl.py", line 77, in <module>
    result = subprocess.run(['python', str(args.train_command), '--stage', str(0), '--stop_epoch', str(int(stop_epoch)), '--model_save_dir', str(model_save_dir), '--segment_pathbase', segment_save_path],  stdout = train_file, check=True)
  File "/home/kjzhao/.conda/envs/ssl/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/train.py', '--stage', '0', '--stop_epoch', '160', '--model_save_dir', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/model_save/0/stage1', '--segment_pathbase', '/home/kjzhao/zhaokj_home/projects/2024/STSSL/STSSL_Segments/']' returned non-zero exit status 1.
```

**Comment by YanhaoWu** [comment]
你batch size设的多大？我感觉可能是单卡的原因，我没有用一张卡跑过，因为那样花费的时间实在是太长了。

**Comment by wslbby** [comment]
在train.py parser里面的batch_size是8，我的卡显存24g，应该是正好，单卡跑通后打算租卡跑。想问下8块3090按照论文中训练200个epoch大概需要多久？

**Comment by YanhaoWu** [comment]
8张的话跑KITTL大概两三天吧，如果你的CPU还可以的话。要不然你发个邮箱，我给你整个pretrained model.

**Comment by YanhaoWu** [comment]
collations函数都是考虑的多卡，所以如果是单卡我猜可能有地方会对不齐，就是导致mask不匹配

**Comment by wslbby** [comment]
好的我试下多卡。邮箱是kjzhao@mail.ecust.edu.cn，多谢！

**Comment by YanhaoWu** [comment]
发了，老哥
